# Generated by Django 3.0.7 on 2021-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50)),
                ('display', models.CharField(default='', max_length=50)),
                ('processor', models.CharField(default='', max_length=50)),
                ('frontcam', models.CharField(default='', max_length=50)),
                ('rearcam', models.CharField(default='', max_length=50)),
                ('batterycap', models.CharField(default='', max_length=50)),
                ('imglink', models.CharField(default='', max_length=300)),
                ('price', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
