# Generated by Django 3.0.7 on 2021-06-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_product_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
    ]
