# Generated by Django 3.0.7 on 2021-06-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='device_name',
            new_name='product_name',
        ),
    ]
